From ubuntu:18.04

RUN 	apt-get update \
	&& apt-get install -y curl git subversion ctags locales net-tools \
	&& apt-get install -y gcc g++ clang python python3 make build-essential cmake python3-dev python-dev node npm\
	&& apt-get install -y software-properties-common vim \
	&& apt-get autoremove 

#系统时间
WORKDIR /root/
ENV 	TZ=Asia/Shanghai
RUN 	ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

#安装vim
ADD	./vim-config/.vimrc 	/root/.vimrc
ADD	./vim-config/.vim	/root/.vim
RUN	mkdir -p /root/.vim/bundle && cd /root/.vim/bundle && git clone https://github.com/VundleVim/Vundle.vim.git \
	&& git clone https://github.com/Valloric/YouCompleteMe.git && cd YouCompleteMe && git submodule update --init --recursive \
	&& YCM_CORES=1 ./install.py --clang-completer --ts-completer\
	&& rm -f /tmp/* \
	&& vim -c 'PluginInstall' -c 'qa!'

#启动命令
COPY	start.sh /bin/start.sh
ENTRYPOINT	["/bin/start.sh"]

